### ISSUE TITLE
Improve Agent's internal logger

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#345]
Child issues:

- [ ] Agent should allow directing its logs to logging backend used by the application #318
- [ ] Make logger less error prone #337
- [ ] Add source analyzer to verify that the class used to create logger is correct #344
- [ ] Setting loglevel in appsettings.json - fetch loglevel for the agent from section "Logging" #338
- [ ] Consider exposing agent's logger as public API (see https://github.com/elastic/apm-agent-dotnet/issues/461). We can consider it "developers only" API since it's not for use in monitored application so we don't need to include it in official documentation (we can still document it at the repo if we choose to do so) and we can be more flexible with keeping it stable.
- [ ] Make logger robust in case of bugs causing re-entrance #494

**Comment by SergeyKleyman** [comment]
I worked a small POC for the new logger design at https://github.com/SergeyKleyman/RunTestsInDocker. As part of POC I implemented bridge with Serilog - https://github.com/SergeyKleyman/RunTestsInDocker/tree/master/Utlz.Logging.Serilog.

**Comment by katzdan** [comment]
Hi,. Need help?

**Comment by SergeyKleyman** [comment]
@katzdan Welcome - help is always appreciated. Would you like to help specifically with the logging part of the agent or with the whole agent in general?

**Comment by katzdan** [comment]
I'm interested in the agent in general. If there are other issues that you think are of higher priority or otherwise more relevant - please let me know.

**Comment by SergeyKleyman** [comment]
@katzdan is there any feature/enhancement you feel agent is missing at the moment? Usually developers are motivated the most when working on features they themselves can use so they understand the use case, the motivation, etc. For example, is there a technology you would like agent to monitor automatically out of the box?

**Comment by katzdan** [comment]
@SergeyKleyman - Hi, I didn't have anything specific in mind , just wanted to contribute as a developer and noticed the 'developer' label in this one. Let me go over the agent in more depth and see if I can come up with some good ideas.
Feel free to offer any other issues for me to handle. small, 'good as first issues' are welcome.
Thanks

**Comment by SergeyKleyman** [comment]
@katzdan I've added `good first issue` label to [a few issues](https://github.com/elastic/apm-agent-dotnet/labels/good%20first%20issue). Please take a look and see if there is anything at which you would like to take a stab.
