### ISSUE TITLE
[meta][docs] Documentation restructure

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-dotnet#572]
A meta issue for tracking documentation improvements outlined in https://github.com/elastic/apm-dev/issues/425.

### Doc restructure
- [x] master - https://github.com/elastic/apm-agent-dotnet/pull/574
- [x] 1.x backport - https://github.com/elastic/apm-agent-dotnet/pull/578

### Build release notes to docs: 
More details: https://github.com/elastic/apm/issues/132.
The PRs in each group must be merged at the same time to prevent breaking the doc build.

#### `master`
- [x] apm-agent-dotnet - https://github.com/elastic/apm-agent-dotnet/pull/575
- [x] docs - https://github.com/elastic/docs/pull/1365

#### `1.x`
- [x] apm-agent-dotnet pr - https://github.com/elastic/apm-agent-dotnet/pull/576
- [x] docs pr - https://github.com/elastic/docs/pull/1366

**Comment by bmorelli25** [comment]
All done!
