### ISSUE TITLE
Prepare preview release 

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#86]
- [x] Create NuGet packages (#85)
- [x] Make sure we can upload to nuget.org
- [x] Make sure the documentation is ok 
- [x] Create blogpost 
- [x] Create walkthrough video

**Comment by alvarolobato** [comment]
@gregkalapos what do you think if we start publishing nightly builds after the preview release?

**Comment by gregkalapos** [comment]
I think it'd be good! https://github.com/elastic/elasticsearch-net already does this (or did, and now moving to another feed, not sure). I think we should sync with them and do the same.

**Comment by Mpdreamz** [comment]
We used to used various myget feeds but recently moved to a single appyveyor feed:

The build for the client is a lot more involved and harder too use as reference, not all will apply to the agent. Will use one of our OSS tooling as reference instead:

Our versioning is very simple:
 https://github.com/nullean/AssemblyRewriter/blob/master/AssemblyRewriter/AssemblyRewriter.csproj#L12-L15

This will release as `<version>-ci<timespan>` unless `/p:Version=<Version>` is specified during `nuget pack -c Release` which will take precedence over the version in the `csproj`. 

Our `appveyor` yaml controls the publish:

https://github.com/nullean/AssemblyRewriter/blob/master/appveyor.yml

It just locates the packages as artifacts and picks those up for the feed. No API keys and separate publish step.

https://ci.appveyor.com/nuget/assemblyrewriter


The client also does the same but we still need to update our README:

https://ci.appveyor.com/nuget/elasticsearch-net

**Comment by gregkalapos** [comment]
Done, we have a release!! 🎉 🎉 🎉 

Blogpost: https://www.elastic.co/blog/elastic-apm-dot-net-agent-preview-released
Video walkthrough: https://www.youtube.com/watch?v=1EyF6JIST_0

I opened a follow up regarding nightly builds: #102.
